ParticleDefinitions[GaugeES] = {
      {SdL,  {  Description -> "Left Down-Squarks"}},
      {SdR,  { Description -> "Right Down-Squarks"}},
      {SuL,  { Description -> "Left Up-Squarks"}}, 
      {SuR,  { Description -> "Right Up-Squarks" }},                
      {SeL,  { Description -> "Left Selectron"}}, 
      {SeR,  { Description -> "Right Selectron"}},                         
      {SvL,  { Description -> "Left Sneutrino"}},                         
      {SHd0, { Description -> "Neutral Down-Higgs"}},                         
      {SHdm, { Description -> "Charged Down-Higgs"}}, 
      {SHu0, { Description -> "Neutral Up-Higgs"}},                         
      {SHup, { Description -> "Charged Up-Higgs"}},                                                   
      {VB,   { Description -> "B-Boson"}},                                                   
      {VG,   { Description -> "Gluon"}},          
      {VWB,  { Description -> "W-Boson"}},          
      {gB,   { Description -> "B-Boson Ghost"}},                                                   
      {gG,   { Description -> "Gluon Ghost" }},          
      {gWB,  { Description -> "W-Boson Ghost"}},    
      {Glu,  { Description -> "Gluino"}},
      {Wino, { Description -> "Wino"}},
      {Bino, { Description -> "Bino"}},                                                                                           
      {H0,   { Description -> "Neutral Higgsinos"}},
      {HC,   { Description -> "Charged Higgsinos"}},

      {SvR,   { Description -> "Right Sneutrino"}},

      {SdeltaL,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\Delta_L",
                 OutputName -> "DeltaL" }},

      {SdeltaL0,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\Delta^0_L",
                 OutputName -> "DeltaL" }},

      {SdeltaLbar,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\overline{\\Delta}_L",
                 OutputName -> "DeltaLbar" }},

      {SdeltaLbar0,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\overline{\\Delta}^0_L",
                 OutputName -> "DeltaLbar" }},

      {SdeltaR,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\Delta_R",
                 OutputName -> "DeltaR" }},

      {SdeltaR0,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\Delta^0_R",
                 OutputName -> "DeltaR" }},

      {SdeltaRbar,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\overline{\\Delta}_R",
                 OutputName -> "DeltaRbar" }},

      {SdeltaRbar0,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\overline{\\Delta}^0_R",
                 OutputName -> "DeltaRbar" }},

      {FdeltaL,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Delta}_L",
                 OutputName -> "FDeltaL" }},

      {FdeltaLbar,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\overline{\\Delta}}_L",
                 OutputName -> "FDeltaLbar" }},

      {FdeltaR,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Delta}_R",
                 OutputName -> "FDeltaR" }},

      {FdeltaRbar,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\overline{\\Delta}}_R",
                 OutputName -> "FDeltaRbar" }},

      {VWL,    {LaTeX -> "W_L" }},
      {VWR,    {LaTeX -> "W_R" }},

      {Fd1,  { Description -> "Dirac Left Down-Quark"}},
      {Fd2,  { Description -> "Dirac Right Down-Quark"}},
      {Fu1,  { Description -> "Dirac Left Up-Quark"}},
      {Fu2,  { Description -> "Dirac Right Up-Quark"}},
      {Fe1,  { Description -> "Dirac Left Electron"}},
      {Fe2,  { Description -> "Dirac Right Electron"}},
      {Fv,   { Description -> "Neutrinos" }},
      
      {DeltaL1, {LaTeX -> "\\delta^L_1"}},
      {DeltaL2, {LaTeX -> "\\delta^L_2"}},
      {DeltaL3, {LaTeX -> "\\delta^L_3"}},
      {DeltaR1, {LaTeX -> "\\delta^R_1"}},
      {DeltaR2, {LaTeX -> "\\delta^R_2"}},
      {DeltaR3, {LaTeX -> "\\delta^R_3"}},
      
      {WinoL, {LaTeX ->"\\tilde{W}_L"}},
      {WinoR, {LaTeX ->"\\tilde{W}_R"}}    
      };

      
   ParticleDefinitions[EWSB] = {
      {Sd ,  { Description -> "Down-Squarks"}},
      {Su ,  { Description -> "Up-Squarks"}},   
      {Se ,  { Description -> "Sleptons"}}, 
      {Sv ,  { Description -> "Sneutrinos"}},                                
      {hh ,  { Description -> "Higgs"}}, 
      {Ah ,  { Description -> "Pseudo-Scalar Higgs"}},                       
      {Hpm,  { Description -> "Charged Higgs"}},                                                   
      {VP,   { Description -> "Photon"}}, 
      {VZ,   { Description -> "Z-Boson" }}, 
      {VG,   { Description -> "Gluon" }},          
      {VWm,  { Description -> "W-Boson" }},         
      {gP,   { Description -> "Photon Ghost"}},                                                   
      {gWm,  { Description -> "Negative W-Boson Ghost"}}, 
      {gWmC, { Description -> "Positive W-Boson Ghost" }}, 
      {gZ,   { Description -> "Z-Boson Ghost" }},
      {gG,   { Description -> "Gluon Ghost" }},             
      {Fd,   { Description -> "Down-Quarks"}},   
      {Fu,   { Description -> "Up-Quarks"}},   
      {Fe,   { Description -> "Leptons" }},
      {Fv,   { Description -> "Neutrinos" }},                                                                     
      {Glu,  { Description -> "Gluino" }},
      {Chi,  { Description -> "Neutralinos"}},
      {Cha,  { Description -> "Charginos"}},                                                                                               
   
    {Hppmm,     { RParity -> 1,
                 Mass ->LesHouches,
                 LaTeX -> "H^{\\pm \\pm}",
                 OutputName -> "Hpp" }},
     
                     
     {VZ1,    { RParity -> 1,  
                 PDG -> 23,
                 Width -> 2.4944, 
                 Mass -> Automatic,
                 FeynArtsNr -> 2,
                 LaTeX -> "Z_1",
                 OutputName -> "Z1" }},

      {VZ2,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "Z_2",
                 OutputName -> "Z2" }},                                        
    
      
      {VW1m,   { RParity -> 1,  
                 PDG -> 24,
                 Width -> 2.08895, 
                 Mass -> Automatic,
                 FeynArtsNr -> 3,
                 LaTeX -> "W_1^-",
                 OutputName -> "W1m" }},

      {VW2m,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "W_2^-",
                 OutputName -> "W2m" }},
     
      
      {gW1m,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 3,
                 LaTeX -> "\\eta_1^-",
                 OutputName -> "gW1m" }}, 
                 
      {gW1mC,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 4,
                 LaTeX -> "\\eta_1^+",
                 OutputName -> "gW1C" }},

      {gW2m,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\eta_2^-",
                 OutputName -> "gW2m" }}, 
                 
      {gW2mC, { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\eta_2^+",
                 OutputName -> "gW2C" }},
      
      {gZ1,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 2,
                 LaTeX -> "\\eta^{Z_1}",
                 OutputName -> "gZ1" }},

      {gZ2,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\eta^{Z_2}",
                 OutputName -> "gZ2" }},
                 
      {Cha2,    { RParity -> -1,  
                 Width -> 0, 
                 Mass -> LesHouches,
                 LaTeX -> "\\chi^{\\pm \\pm}",
                 OutputName -> "CA2" }}
        };    
        
        
        
WeylFermionAndIndermediate = {
       {FHd0, { Description -> "Neutral Down-Higgsino"}},      
       {FHu0, { Description -> "Neutral Up-Higgsino" }}, 
       {FHdm, { Description -> "Charged Down-Higgsino"}},                                                                                                             
       {FHup, { Description -> "Charged Up-Higgsino"}},
       {L0,   { Description -> "Neutralino Weyl-Spinor"}},
       {Lm,   { Description -> "Negative Chargino Weyl-Spinor"}},
       {Lp,   { Description -> "Positive Chargino Weyl-Spinor"}}, 
       {fG,   { Description ->"Gluino Weyl-Spinor"}},
       {fWB,  { Description ->"Wino Weyl-Spinor"}},
       {fW0,  { Description ->"Neutral Wino" }},
       {fWm,  { Description ->"Negative Wino"}},                 
       {fWp,  { Description ->"Positive Wino"}},                 
       {fB,   { Description ->"Bino Weyl-Spinor"}},    
       {phid, { Description -> "Scalar Down"}},                                                                       
       {phiu, { Description -> "Scalar Up"}}, 
       {sigmad,   { Description -> "Pseudo Scalar Down"}},                                                                                        
       {sigmau,   { Description -> "Pseudo Scalar Up" }},
       {SHd,  { Description -> "Down-Higgs"}},
       {SHu,  { Description -> "Up-Higgs"}},
       {Sl,   { Description -> "Left Slepton" }},
       {Sq,   { Description -> "Left Squark" }},
       {FeL,  { Description -> "Left Electron" }},
       {FeR,  { Description -> "Right Electron" }} ,
       {FdL,  { Description -> "Left Down-Quark" }},
       {FdR,  { Description -> "Right Down-Quark" }},              
       {FuL,  { Description -> "Left Up-Quark" }},
       {FuR,  { Description -> "Right Up-Quark" }},
       {FEL,  { Description -> "Rotated Left Electron" }},
       {FER,  { Description -> "Rotated Right Electron" }} ,
       {FDL,  { Description -> "Rotated Left Up-Quark" }},
       {FDR,  { Description -> "Rotated Right Up-Quark" }},              
       {FUL,  { Description -> "Rotated Left Down-Quark"}},
       {FUR,  { Description -> "Rotated Right Down-Quark" }},                
       {FHd,  { Description -> "Down-Higgsino" }},
       {FHu,  { Description -> "Up-Higgsino" }},
       {Fl,   { Description -> "Left Leptons"}},
       {Fq,   { Description -> "Left Quarks"}},  
       {FvL,  { Description -> "Left Neutrino"}},                  
       {FvR,  { Description -> "Right Neutrino"}},

                  

   {FdeltaRm,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Delta}_R^-",
                 OutputName -> "" }},                             
   
{FdeltaLbarm,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\overline{\\Delta}}_L^-",
                 OutputName -> "" }},

{FdeltaRbarp,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\overline{\\Delta}}_R^+",
                 OutputName -> "" }},                             
   
   {FdeltaLp,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Delta}_L^+",
                 OutputName -> "" }},

  {FdeltaR0,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Delta}_R^0",
                 OutputName -> "" }},                             
   
{FdeltaLbar0,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\overline{\\Delta}}_L^0",
                 OutputName -> "" }},

{FdeltaRbar0,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\overline{\\Delta}}_R^0",
                 OutputName -> "" }},                             
   
   {FdeltaL0,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Delta}_L^0",
                 OutputName -> "" }},
                 
                  
       {fWL,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\lambda_{\\tilde{W}_L}",
                 OutputName -> "" }},

       {fWR,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\lambda_{\\tilde{W}_R}",
                 OutputName -> "" }},
       
       {fW0,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{W}^0",
                 OutputName -> "" }},

       {fWL0,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{W}_L^0",
                 OutputName -> "" }},

       {fWR0,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{W}_R^0",
                 OutputName -> "" }},
                 
       {fW1m,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{W}_1^-",
                 OutputName -> "" }},
                 
       {fW1p,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{W}_1^+",
                 OutputName -> "" }},

       {fW2m,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{W}_2^-",
                 OutputName -> "" }},
                 
       {fW2p,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{W}_2^+",
                 OutputName -> "" }},
                 
 
       {phiR,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\phi_{R}",
                 OutputName -> "" }},

       {phiL,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\phi_{L}",
                 OutputName -> "" }},

    {phiRbar,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\phi_{\\overline{R}}",
                 OutputName -> "" }},

    {phiLbar,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\phi_{\\overline{L}}",
                 OutputName -> "" }},

    {sigmad,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\sigma_{d}",
                 OutputName -> "" }},                                                                                        
    {sigmau,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\sigma_{u}",
                 OutputName -> "" }},

    {sigmaR,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\sigma_{R}",
                 OutputName -> "" }},

    {sigmaL,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\sigma_{L}",
                 OutputName -> "" }},

 {sigmaRbar,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\sigma_{\\overline{R}}",
                 OutputName -> "" }},

 {sigmaLbar,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\sigma_{\\overline{L}}",
                 OutputName -> "" }},

   {SdeltaLp,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\Delta_L^+",
                 OutputName -> "DeltaLp" }},

  {SdeltaLbarm,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\overline{\\Delta}_L^-",
                 OutputName -> "DeltaLbarm" }},

     {SdeltaRm,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\Delta_R^-",
                 OutputName -> "DeltaRm" }},

  {SdeltaRbarp,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\overline{\\Delta}_R^+",
                 OutputName -> "DeltaRbarp" }},

   {SdeltaLpp,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\Delta_L^{++}",
                 OutputName -> "DeltaLpp" }},

 {SdeltaLbarmm,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\overline{\\Delta}_L^{--}",
                 OutputName -> "DeltaLbarmm" }},

    {SdeltaRmm,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\Delta_R^{--}",
                 OutputName -> "DeltaRmm" }},

 {SdeltaRbarpp,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\overline{\\Delta}_R^{++}",
                 OutputName -> "DeltaRbarpp" }},

  {FdeltaLpp,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Delta}_L^{++}",
                 OutputName -> "FDeltaLpp" }},

 {FdeltaLbarmm,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\overline{\\Delta}}_L^{--}",
                 OutputName -> "FDeltaLbarmm" }},

    {FdeltaRmm,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Delta}_R^{--}",
                 OutputName -> "FDeltaRmm" }},

 {FdeltaRbarpp,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\overline{\\Delta}}_R^{++}",
                 OutputName -> "FDeltaRbarpp" }},

       {FqL,   { LaTeX -> "q_L" }},
       {FqR,   { LaTeX -> "q_R" }},
       {FlL,   { LaTeX -> "l_L" }},
       {FlR,   { LaTeX -> "l_R" }},
       {FPhi,   { LaTeX -> "\\phi" }},
       {FdeltaL,   { LaTeX -> "\\Delta_L" }},
       {FdeltaLbar,   { LaTeX -> "\\overline{\\Delta}_L" }},
       {FdeltaR,   { LaTeX -> "\\Delta_R" }},
       {FdeltaRbar,   { LaTeX -> "\\overline{\\Delta}_R" }},

       {SqL,   { LaTeX -> "\\tilde{q}_L" }},
       {SqR,   { LaTeX -> "\\tilde{q}_R" }},
       {SlL,   { LaTeX -> "\\tilde{l}_L" }},
       {SlR,   { LaTeX -> "\\tilde{l}_R" }},
       {SPhi,   { LaTeX -> "\\tilde{\\phi}" }},
       {SdeltaL,   { LaTeX -> "\\tilde{\\Delta}_L" }},
       {SdeltaLbar,   { LaTeX -> "\\tilde{\\overline{\\Delta}}_L" }},
       {SdeltaR,   { LaTeX -> "\\tilde{\\Delta}_R" }},
       {SdeltaRbar,   { LaTeX -> "\\tilde{\\overline{\\Delta}}_R" }},

       {Dmm,   { LaTeX -> "\\Delta^{--}" }},
       {Dpp,   { LaTeX -> "\\Delta^{++}" }},              

               
       {G,    { Description -> "Gluon Superfield" }},                 
       {B,    { Description -> "B Superfield" }},                 
       {WL,   { LaTeX -> "\\hat{W}_L" }},
       {WR,   { LaTeX -> "\\hat{W}_R" }},
       {qL,   { LaTeX -> "\\hat{q}_L" }},
       {qR,   { LaTeX -> "\\hat{q}_R" }},
       {lL,   { LaTeX -> "\\hat{l}_L" }},
       {lR,   { LaTeX -> "\\hat{l}_R" }},
       {Phi,   { LaTeX -> "\\hat{\\phi}" }},
       {deltaL,   { LaTeX -> "\\hat{\\Delta}_L" }},
       {deltaLbar,   { LaTeX -> "\\hat{\\overline{\\Delta}}_L" }},
       {deltaR,   { LaTeX -> "\\hat{\\Delta}_R" }},
       {deltaRbar,   { LaTeX -> "\\hat{\\overline{\\Delta}}_R" }}
       

        };       


