
ParticleDefinitions[GaugeES] = {

      {SdL,  {  RParity -> -1,
                PDG ->  {0,0,0},
                Width -> {0, 0, 0},
                Mass -> Automatic,   
                LaTeX -> "\\tilde{d}",
                FeynArtsNr -> 14,
                OutputName -> "dL" }},              
              
      {SdR,  { RParity -> -1,  
               PDG -> {0, 0, 0},
               Width -> {0, 0, 0}, 
               Mass -> Automatic,
               FeynArtsNr -> 15,
               LaTeX -> "\\tilde{d}^c",
               OutputName -> "dR" }},
               
       {SuL,  { RParity -> -1,  
               PDG -> {0, 0, 0},
               Width -> {0, 0, 0}, 
               Mass -> Automatic,
               FeynArtsNr -> 16,
               LaTeX -> "\\tilde{u}",
               OutputName -> "uL" }}, 
               
       {SuR,  { RParity -> -1,  
               PDG -> {0, 0, 0},
               Width -> {0, 0, 0}, 
               Mass -> Automatic,
               FeynArtsNr -> 17,
               LaTeX -> "\\tilde{u}^c",
               OutputName -> "uR" }},
      
       {SeL,  { RParity -> -1,  
               PDG -> {0, 0, 0},
               Width -> {0, 0, 0}, 
               Mass -> Automatic,
               FeynArtsNr -> 12,
               LaTeX -> "\\tilde{e}",
               OutputName -> "eL" }}, 
               
       {SeR,  { RParity -> -1,  
               PDG -> {0, 0, 0},
               Width -> {0, 0, 0}, 
               Mass -> Automatic,
               FeynArtsNr -> 13,
               LaTeX -> "\\tilde{e}^c",
               OutputName -> "eR" }},
     
       {SvL,  { RParity -> -1,  
               PDG -> {0, 0, 0},
               Width -> {0, 0, 0}, 
               Mass -> Automatic,
               FeynArtsNr -> 10,
               LaTeX -> "\\tilde{\\nu}",
               OutputName -> "nL" }},

       {SvR,  { RParity -> -1,  
               PDG -> {0, 0, 0},
               Width -> {0, 0, 0}, 
               Mass -> Automatic,
               LaTeX -> "\\tilde{\\nu}^c",
               OutputName -> "nR" }},
      
      {SHd0,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 1,
                 LaTeX -> "H_d^0",
                 OutputName -> "Hd0" }},
      
      {SHdm,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 2,
                 LaTeX -> "H_d^-",
                 OutputName -> "Hdm" }}, 
                 
      {SHu0,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 3,
                 LaTeX -> "H_u^0",
                 OutputName -> "Hu0" }},
      
      {SHup,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 4,
                 LaTeX -> "H_u^+",
                 OutputName -> "Hup" }},      
     
      {VB,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 1,
                 LaTeX -> "B",
                 OutputName -> "B" }},
    
      {VG,    { RParity -> 1,  
                 PDG -> 21,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 5,
                 LaTeX -> "G",
                 OutputName -> "G" }},
     
      {VWL,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 2,
                 LaTeX -> "W_L",
                 OutputName -> "WL" }},

      {VWR,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "W_R",
                 OutputName -> "WR" }},
     
      {gB,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 1,
                 LaTeX -> "\\eta^B",
                 OutputName -> "gB" }},
    
      {gG,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 5,
                 LaTeX -> "\\eta^G",
                 OutputName -> "gG" }},
     
      {gWL,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 2,
                 LaTeX -> "\\eta^{W_L}",
                 OutputName -> "gWL" }},

      {gWR,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\eta^{W_R}",
                 OutputName -> "gWR" }},    
                 
      {Fd,    { RParity -> 1,  
                 PDG -> {1,3,5},
                 Width -> {0, 0, 0}, 
                 Mass -> Automatic,
                 FeynArtsNr -> 4,
                 LaTeX -> "d",
                 OutputName -> "d" }},   
                 
      {Fu,    { RParity -> 1,  
                 PDG -> {2,4,6},
                 Width -> {0, 0, 0}, 
                 Mass -> Automatic,
                 FeynArtsNr -> 3,
                 LaTeX -> "u",
                 OutputName -> "u" }},   
                 
      {Fe,    { RParity -> 1,  
                 PDG -> {11,13,15},
                 Width -> {0, 0, 0}, 
                 Mass -> Automatic,
                 FeynArtsNr -> 2,
                 LaTeX -> "e",
                 OutputName -> "e" }},
                 
      {Fv,    { RParity -> 1,  
                 PDG -> {12,14,16},
                 Width -> {0, 0, 0}, 
                 Mass -> Automatic,
                 FeynArtsNr -> 1,
                 LaTeX -> "\\nu",
                 OutputName -> "n" }},                                                                                      
      {Glu,    { RParity -> -1,  
                 PDG -> 100039,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 15,
                 LaTeX -> "\\tilde{g}",
                 OutputName -> "g" }},
                 
      {Wino,    { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 12,
                 LaTeX -> "\\tilde{W}",
                 OutputName -> "w" }},
                 
      {Bino,    { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 11,
                 LaTeX -> "\\tilde{B}",
                 OutputName -> "b" }},              
     
      {HD0,    { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 21,
                 LaTeX -> "\\tilde{H_d^0}",
                 OutputName -> "HD0" }},
        
      {HU0,    { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 22,
                 LaTeX -> "\\tilde{H_u^0}",
                 OutputName -> "HU0" }},
        
      {HDm,    { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 23,
                 LaTeX -> "\\tilde{H_d^-}",
                 OutputName -> "HDM" }},
        
      {HUp,    { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 24,
                 LaTeX -> "\\tilde{H_u^+}",
                 OutputName -> "HUP" }},

      {SdeltaL,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\Delta",
                 OutputName -> "DeltaL" }},

      {SdeltaLbar,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\overline{\\Delta}",
                 OutputName -> "DeltaLbar" }},

      {SdeltaR,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\Delta^c",
                 OutputName -> "DeltaR" }},

      {SdeltaRbar,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\overline{\\Delta}^c",
                 OutputName -> "DeltaRbar" }},

      {FdeltaL,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Delta}",
                 OutputName -> "FDeltaL" }},

      {FdeltaLbar,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\overline{\\Delta}}^c",
                 OutputName -> "FDeltaLbar" }},

      {FdeltaR,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Delta}^c",
                 OutputName -> "FDeltaR" }},

      {FdeltaRbar,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\overline{\\Delta}}^c",
		 OutputName -> "FDeltaRbar" }},

      {SomegaL,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\Omega",
                 OutputName -> "OmegaL" }},

      {SomegaR,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\Omega^c",
                 OutputName -> "OmegaR" }},

      {FomegaL,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Omega}",
                 OutputName -> "FOmegaL" }},

      {FomegaR,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Omega}^c",
                 OutputName -> "FOmegaR" }}
      };

      
  ParticleDefinitions[EWSB] = {
    
      
     {Hpm,     { RParity -> 1,
                 Mass ->LesHouches,
                 FeynArtsNr -> 3,
                 LaTeX -> "H^\\pm",
                 OutputName -> "Hp" }},

      {VB,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 1,
                 LaTeX -> "B",
                 OutputName -> "B" }},
    
      {VG,    { RParity -> 1,  
                 PDG -> 21,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 5,
                 LaTeX -> "G",
                 OutputName -> "G" }},
     
      {VWL,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 2,
                 LaTeX -> "W_L",
                 OutputName -> "WL" }},
     
      {VWRm,   { RParity -> 1,
                 Mass -> Automatic,
                 LaTeX -> "W_R^-",
                 OutputName -> "WRm" }},

      {VWR0,   { RParity -> 1,
                 Mass -> Automatic,
                 LaTeX -> "W_R^0",
                 OutputName -> "WR0" }},

      {gB,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 1,
                 LaTeX -> "\\eta^B",
                 OutputName -> "gB" }},
    
      {gG,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 5,
                 LaTeX -> "\\eta^G",
                 OutputName -> "gG" }},
     
      {gWL,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 2,
                 LaTeX -> "\\eta^{W_L}",
                 OutputName -> "gWL" }},

      {gWRm,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 3,
                 LaTeX -> "\\eta_R^-",
                 OutputName -> "gWRm" }}, 
                 
      {gWRmC,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 4,
                 LaTeX -> "\\eta_R^+",
                 OutputName -> "gWRC" }},

      {gWR0,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 FeynArtsNr -> 3,
                 LaTeX -> "\\eta_R^0",
                 OutputName -> "gWR0" }},            
      
      {Glu,    { RParity -> -1,  
                 PDG -> 100039,
                 Width -> 0, 
                 Mass -> LesHouches,
                 FeynArtsNr -> 15,
                 LaTeX -> "\\tilde{g}",
                 OutputName -> "g" }},
                 
      {ChiR1,    { RParity -> -1,
                 Width -> 0, 
                 Mass -> LesHouches,
                 FeynArtsNr -> 11,
                 LaTeX -> "\\tilde{\\chi}^0",
                 OutputName -> "C0" }},
                 
      {Cha1r1,    { RParity -> -1,
                 Width -> 0, 
                 Mass -> LesHouches,
                 FeynArtsNr -> 12,
                 LaTeX -> "\\chi^{\\pm}",
                 OutputName -> "CA" }},
                 
       {Hpm1R1, {LaTeX -> "\\delta^{c-}"}},
       {Hpm2R1, {LaTeX -> "\\omega^{c-}"}},
       
       
          {SDLr1, {LaTeX -> "\\tilde{D}_L"}},
    {SULr1, {LaTeX -> "\\tilde{U}_L"}},
    {SDRr1, {LaTeX -> "\\tilde{D}_R"}},
    {SURr1, {LaTeX -> "\\tilde{U}_R"}},
    {SELr1, {LaTeX -> "\\tilde{E}_L"}},
    {SERr1, {LaTeX -> "\\tilde{E}_R"}},
    {SVLr1, {LaTeX -> "\\tilde{V}_L"}},
    {SVRr1, {LaTeX -> "\\tilde{V}_R"}},
    {SH0r1, {LaTeX -> "H"}},
    {SHCr1, {LaTeX -> "H^-"}},
    {SO1r1, {LaTeX -> "\\omega"}},
    {SDLpR1, {LaTeX -> "\\delta^+"}},
        {SDL0R1, {LaTeX -> "\\delta^0"}},
    {SDLppR1, {LaTeX -> "\\delta^{++}"}},
    {SDRmmR1, {LaTeX -> "\\delta^{c --}"}},
    {SDR0r1, {LaTeX -> "\\delta^{c 0}"}}
       
        };    
        
        
        
 WeylFermionAndIndermediate = {
       {FHd0,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{H}_d^0",
                 OutputName -> "" }},      
                 
       {FHu0,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{H}_u^0",
                 OutputName -> "" }}, 
                 
       {FHdm,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{H}_d^-",
                 OutputName -> "" }},                             
   
       {FHup,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{H}_u^+",
                 OutputName -> "" }},

       {FvL,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\nu_L",
                 OutputName -> "" }},                             
   
       {FvR,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\nu_R",
                 OutputName -> "" }},

   {FomegaLm,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Omega}^-",
                 OutputName -> "" }},

   {FomegaRm,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Omega}^{c -}",
                 OutputName -> "" }},

   {FdeltaRm,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Delta}^{c-}",
                 OutputName -> "" }},                             
   
{FdeltaLbarm,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\overline{\\Delta}}^-",
                 OutputName -> "" }},

{FdeltaRbarp,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\overline{\\Delta}}^{c +}",
                 OutputName -> "" }},                             
   
   {FdeltaLp,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Delta}^+",
                 OutputName -> "" }},

  {FomegaL0,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Omega}^0",
                 OutputName -> "FOmegaL0" }},

  {FomegaR0,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Omega}^{c 0}",
                 OutputName -> "FOmegaR0" }},

  {FdeltaR0,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Delta}^{c 0}",
                 OutputName -> "" }},                             
   
{FdeltaLbar0,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\overline{\\Delta}}^0",
                 OutputName -> "" }},

{FdeltaRbar0,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\overline{\\Delta}}^{c 0}",
                 OutputName -> "" }},                             
   
   {FdeltaL0,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Delta}^0",
                 OutputName -> "" }},

        {N0,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\lambda_{\\nu}^0",
                 OutputName -> "" }},
                 
        {L0,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\lambda^0",
                 OutputName -> "" }},
                 
        {Lm,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\lambda^-",
                 OutputName -> "" }},
                 
       {Lp,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\lambda^+",
                 OutputName -> "" }},
                 
       {fG,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{G}",
                 OutputName -> "" }},
                 
       {fWL,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{W}_L",
                 OutputName -> "" }},

       {fWR,   { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{W}_R",
                 OutputName -> "" }},

       {fWL0,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{W}_L^0",
                 OutputName -> "" }},

       {fWR0,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{W}_R^0",
                 OutputName -> "" }},
                 
       {fWRm,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{W}_R^-",
                 OutputName -> "" }},
                 
       {fWRp,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{W}_R^+",
                 OutputName -> "" }},
                 
       {fB,    { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{B}",
                 OutputName -> "" }},    
                 
       {phid,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\phi_{d}",
                 OutputName -> "" }},

       {phiu,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\phi_{u}",
                 OutputName -> "" }},

       {phiR,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\phi^c",
                 OutputName -> "" }},

       {phiL,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\phi",
                 OutputName -> "" }},

    {phiRbar,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\overline{\\phi}^c",
                 OutputName -> "" }},

    {phiLbar,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\overline{\\phi}",
                 OutputName -> "" }},

    {phiOmL,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\phi_{\\Omega}",
                 OutputName -> "" }},

    {phiOmR,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\phi^c_{\\Omega}",
                 OutputName -> "" }},

    {sigmad,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\sigma_{d}",
                 OutputName -> "" }},                                                                                        
    {sigmau,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\sigma_{u}",
                 OutputName -> "" }},

    {sigmaR,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\sigma^c",
                 OutputName -> "" }},

    {sigmaL,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\sigma",
                 OutputName -> "" }},

 {sigmaRbar,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\overline{\\sigma}^c",
                 OutputName -> "" }},

 {sigmaLbar,   { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\overline{\\sigma}",
                 OutputName -> "" }},

 {sigmaOmL,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\sigma_{\\Omega}",
                 OutputName -> "" }},

 {sigmaOmR,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\sigma_{\\Omega^c}",
                 OutputName -> "" }},

   {SdeltaLp,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\Delta^+",
                 OutputName -> "DeltaLp" }},

   {SdeltaL0,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\Delta^0",
                 OutputName -> "DeltaL0" }},

  {SdeltaLbarm,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> {"\\overline{\\Delta}^-","\\overline{\\Delta}^+"},
                 OutputName -> "DeltaLbarm" }},

  {SdeltaLbar0,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\overline{\\Delta}^0",
                 OutputName -> "DeltaLbar0" }},

     {SdeltaRm,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> {"\\Delta^{c -}","\\Delta^{c +}"} ,
                 OutputName -> "DeltaRm" }},

     {SdeltaR0,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\Delta^{c 0}",
                 OutputName -> "DeltaR0" }},

  {SdeltaRbarp,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> {"\\overline{\\Delta}^{c +}","\\overline{\\Delta}^{c -}"},
                 OutputName -> "DeltaRbarp" }},

  {SdeltaRbar0,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\overline{\\Delta}^{c 0}",
                 OutputName -> "DeltaRbar0" }},

   {SdeltaLpp,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> {"\\Delta^{++}","\\Delta^{--}"},
                 OutputName -> "DeltaLpp" }},

 {SdeltaLbarmm,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> {"\\overline{\\Delta}^{--}","\\overline{\\Delta}^{++}"},
                 OutputName -> "DeltaLbarmm" }},

    {SdeltaRmm,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> {"\\Delta^{c --}","\\Delta^{c ++}"},
                 OutputName -> "DeltaRmm" }},

 {SdeltaRbarpp,  { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> {"\\overline{\\Delta}^{c ++}","\\overline{\\Delta}^{c --}"},
                 OutputName -> "DeltaRbarpp" }},

 {SomegaLm,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> {"\\Omega^{-}","\\Omega^{+}"},
                 OutputName -> "OmegaLm" }},

 {SomegaLp,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> {"\\Omega^{+}","\\Omega^{-}"},
                 OutputName -> "OmegaLp" }},

 {SomegaL0,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\Omega^{0}",
                 OutputName -> "OmegaL0" }},

 {SomegaRm,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\Omega^{c -}",
                 OutputName -> "OmegaRm" }},

 {SomegaRp,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\Omega^{c +}",
                 OutputName -> "OmegaRp" }},

 {SomegaR0,    { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\Omega^{c 0}",
                 OutputName -> "OmegaR0" }},

  {FdeltaLpp,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Delta}^{++}",
                 OutputName -> "FDeltaLpp" }},

 {FdeltaLbarmm,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\overline{\\Delta}}^{--}",
                 OutputName -> "FDeltaLbarmm" }},

    {FdeltaRmm,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Delta}^{c --}",
                 OutputName -> "FDeltaRmm" }},

 {FdeltaRbarpp,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\overline{\\Delta}}^{c ++}",
                 OutputName -> "FDeltaRbarpp" }},

  {FomegaLm,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Omega}^{-}",
                 OutputName -> "FOmegaLm" }},

  {FomegaLp,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Omega}^{+}",
                 OutputName -> "FOmegaLp" }},

  {FomegaRm,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Omega}^{c -}",
                 OutputName -> "FOmegaRm" }},

  {FomegaRp,  { RParity -> -1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{\\Omega}^{c +}",
                 OutputName -> "FOmegaRp" }},

    {SHd,      { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "H_d",
                 OutputName -> "" }},
                                                                            
   {SHu,      { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "H_u",
                 OutputName -> "" }},
      
   {Sl,      { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{L}",
                 OutputName -> "" }},

   {Sq,      { RParity -> 1,  
                 PDG -> 0,
                 Width -> 0, 
                 Mass -> Automatic,
                 LaTeX -> "\\tilde{Q}",
                 OutputName -> "" }},
                 
       {e,    { Description -> "Right Electron Superfield" }},
       {d,    { Description -> "Right Down-Quark Superfield" }},                 
       {q,    { Description -> "Left Quark Superfield" }},                 
       {u,    { Description -> "Right Up-Quark Superfield" }},                 
       {l,    { Description -> "left Lepton Superfield" }},  
       {Hd,   { Description -> "Down-Higgs Superfield"}},                                         
       {Hu,   { Description -> "Up-Higgs Superfield" }},                 
       {G,    { Description -> "Gluon Superfield" }},                 
       {B,    { Description -> "B Superfield" }},                 
       {WB,   { Description -> "W Superfield" }},
       {deltaR0, {LaTeX -> "\\hat{\\Delta}^{c 0}"}},
       {deltaRbar0, {LaTeX -> "\\hat{\\bar{\\Delta}}^{c 0}"}},
       {omegaR0, {LaTeX -> "\\hat{\\Omega}^{c 0}"}},
       {omegaL, {LaTeX -> "\\hat{\\Omega}"}},
       {FomegaR0, {LaTeX -> "\\Omega^{c 0}"}},
       {FomegaL, {LaTeX -> "\\Omega"}},
       {SomegaR0, {LaTeX -> "\\tilde{\\Omega}^{c 0}"}},
       {SomegaL, {LaTeX -> "\\tilde{\\Omega}"}},
       {Sl,   { Description -> "Left Slepton" }},
       {Sq,   { Description -> "Left Squark" }},
       {FHd,  { Description -> "Down-Higgsino" }},
       {FHu,  { Description -> "Up-Higgsino" }},
       {Fl,   { Description -> "Left Leptons"}},
       {Fq,   { Description -> "Left Quarks"}}, 
       {WL, {LaTeX -> "\\hat{W}_L"}},
       {WR, {LaTeX -> "\\hat{W}_R"}},
       {fWL, {LaTeX -> "\\tilde{W}_L"}},
       {fWR, {LaTeX -> "\\tilde{W}_R"}},
       {VWR, {LaTeX -> "W_R"}},
       {VWL, {LaTeX -> "W_L"}},
              {fWB,  { Description ->"Wino Weyl-Spinor"}},
       {fW0,  { Description ->"Neutral Wino" }},
       {fWm,  { Description ->"Negative Wino"}},                 
       {fWp,  { Description ->"Positive Wino"}},                 
       {fB,   { Description ->"Bino Weyl-Spinor"}},
       {qL, {LaTeX -> "\\hat{Q}"}},                   
       {qR, {LaTeX -> "\\hat{Q}^c"}},
       {lL, {LaTeX -> "\\hat{L}"}},
       {lR, {LaTeX -> "\\hat{L}^c"}},
       {Phi, {LaTeX -> "\\hat{\\Phi}"}},
       {deltaL, {LaTeX -> "\\hat{\\Delta}"}},
       {deltaLbar, {LaTeX -> "\\hat{\\bar{\\Delta}}"}},
       {deltaR, {LaTeX -> "\\hat{\\Delta}^c"}},
       {deltaRbar, {LaTeX -> "\\hat{\\bar{\\Delta}}^c"}},
        {omegaL, {LaTeX -> "\\hat{\\Omega}"}},
        {omegaR, {LaTeX -> "\\hat{\\Omega}^c"}},
       {SqL, {LaTeX -> "\\hat{Q}"}},                   
       {SqR, {LaTeX -> "\\tilde{Q}^c"}},
       {SlL, {LaTeX -> "\\tilde{L}"}},
       {SlR, {LaTeX -> "\\tilde{L}^c"}},
       {SPhi, {LaTeX -> "\\tilde{\\Phi}"}},
       {FqL, {LaTeX -> "Q"}},                   
       {FqR, {LaTeX -> "Q^c"}},
       {FlL, {LaTeX -> "L"}},
       {FlR, {LaTeX -> "L^c"}},
       {FPhi, {LaTeX -> "\\Phi"}}
      



        };       


